version: '2'

services:
#  eureka-server:
#    build: eureka-server/
#    container_name: eureka-server
#    restart: always
#    network_mode: "host"
#    hostname: localhost
#    ports:
#      - 8085:8085
#
#  config-server:
#    build: config-server/
#    container_name: config-server
#    restart: always
#    network_mode: "host"
#    hostname: localhost
#    ports:
#      - 8888:8888
#
#  api-gateway:
#    build: api-gateway/
#    container_name: api-gateway
#    depends_on:
#      - config-server
#      - eureka-server
#    restart: always
#    network_mode: "host"
#    hostname: localhost
#    ports:
#      - 8080:8080
#
#  mongo:
#    image: mongo
#    container_name: mongo
#    restart: always
#    ports:
#      - 27017:27017
#    network_mode: host
#    volumes:
#      - $HOME/mongo:/data/db
#


 rabbitmq:
   image: rabbitmq:3-management
   container_name: rabbitmq
   restart: always
   ports:
     - 5672:5672
     - 15672:15672
   hostname: localhost
   network_mode: host


 neo4jdb:
  image: neo4j:latest
  container_name: testneo4j
  volumes:
    - ./ne04j/data:/data
    - ./ne04j/import:/var/lib/neo4j/import
  ports:
    - 7474:7474
    - 7687:7687
  environment:
    - NEO4J_AUTH=neo4j/test
  network_mode: "host"
  hostname: localhost
  restart: always

